name: excellence_coaching_hub
description: ExcellenceCoachingHub e-learning platform
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  riverpod: ^2.6.1
  flutter_riverpod: ^2.6.1
  http: ^1.2.2
  shared_preferences: ^2.3.2
  flutter_secure_storage: ^9.2.4
  json_annotation: ^4.9.0
  freezed_annotation: ^2.4.4
  go_router: ^17.1.0
  video_player: ^2.9.2
  chewie: ^1.8.5
  pdf: ^3.11.1
  path_provider: ^2.1.5
  dio: ^5.4.0
  permission_handler: ^11.3.0
  intl: ^0.20.2
  package_info_plus: ^8.3.1
  google_sign_in: ^6.3.0
  image_picker: ^1.1.2
  mime: ^2.0.0
  path: ^1.9.0
  http_parser: ^4.0.2
  url_launcher: ^6.3.0
  share_plus: ^10.1.2
  file_picker: ^8.0.3
  audioplayers: ^6.0.0
  flutter_tts: ^4.0.0
  # record: ^5.1.2  # Temporarily removed due to Linux compatibility issues

  firebase_auth: ^6.1.4
  firebase_core: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.5.4
  json_serializable: ^6.9.5
  freezed: ^2.5.8
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/icon.png"
    background_color: "#2196F3"
    theme_color: "#2196F3"
  windows:
    generate: true
    image_path: "assets/icon.png"
    icon_size: 256
  macos:
    generate: true
    image_path: "assets/icon.png"
  linux:
    generate: true
    image_path: "assets/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/