name: excellencecoachinghub
description: ExcellenceCoachingHub e-learning platform
publish_to: 'none'
version: 1.0.1+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  riverpod: ^2.6.1
  flutter_riverpod: ^2.6.1
  http: ^1.2.2
  shared_preferences: ^2.3.2
  flutter_secure_storage: ^9.2.4
  json_annotation: ^4.9.0
  freezed_annotation: ^3.1.0
  go_router: ^17.1.0
  video_player: ^2.9.2
  chewie: ^1.8.5
  pdf: ^3.11.1
  path_provider: ^2.1.5
  dio: ^5.4.0
  permission_handler: ^12.0.1
  intl: ^0.20.2
  package_info_plus: ^9.0.0
  google_sign_in: ^6.2.1
  image_picker: ^1.1.2
  mime: ^2.0.0
  path: ^1.9.0
  http_parser: ^4.0.2
  url_launcher: ^6.3.0
  share_plus: ^12.0.1
  file_picker: ^10.3.10
  audioplayers: ^6.0.0
  flutter_tts: ^4.0.0
  device_info_plus: ^10.0.0
  uuid: ^4.5.1
  # record: ^5.1.2  # Temporarily removed due to Linux compatibility issues

  firebase_auth: ^5.3.1
  firebase_core: ^3.6.0
  firebase_messaging: ^15.1.3
  flutter_local_notifications: ^17.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.5.4
  json_serializable: ^6.9.5
  freezed: ^3.2.5
  flutter_launcher_icons: ^0.14.4
  msix: ^3.16.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/icon.png"
    background_color: "#2196F3"
    theme_color: "#2196F3"
  windows:
    generate: true
    image_path: "assets/icon.png"
    icon_size: 256
  macos:
    generate: true
    image_path: "assets/icon.png"
  linux:
    generate: true
    image_path: "assets/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/

msix_config:
  display_name: excellencecoachinghub
  publisher_display_name: ECH
  publisher: CN=6B4466E8-E27C-410F-804C-21877F7B22F6
  identity_name: ECH.excellencecoachinghub
  msix_version: 1.0.1.0
  logo_path: windows/runner/resources/app_icon.ico
  store: true
  store_id: 9NW5V60BNHNN
  certificate_path: ExcellenceHubCert.pfx
  certificate_password: Excellence123!