name: excellence_coaching_hub
description: ExcellenceCoachingHub e-learning platform
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  riverpod: ^2.5.1
  flutter_riverpod: ^2.5.1
  http: ^1.1.0
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0
  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1
  go_router: ^12.1.3
  video_player: ^2.7.2
  chewie: ^1.7.4
  pdf: ^3.10.8
  path_provider: ^2.1.1
  intl: ^0.19.0
  package_info_plus: ^8.0.0
  google_sign_in: ^6.2.1
  image_picker: ^1.0.4
  mime: ^1.0.4

  firebase_auth: ^5.7.0
  firebase_core: ^3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.8
  json_serializable: ^6.7.1
  freezed: ^2.5.2
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/icon.png"
    background_color: "#2196F3"
    theme_color: "#2196F3"
  windows:
    generate: true
    image_path: "assets/icon.png"
    icon_size: 256
  macos:
    generate: true
    image_path: "assets/icon.png"
  linux:
    generate: true
    image_path: "assets/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/